global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_app"
    static_configs:
      - targets: ["node_app:3000"]

  - job_name: "jmeter"
    static_configs:
      - targets: ["jmeter:9270"]
